# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mocktail < Formula
  desc "Naive code generator that creates mock implementation using testify.mock.
"
  homepage "https://github.com/traefik/mocktail"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/traefik/mocktail/releases/download/v0.2.1/mocktail_v0.2.1_darwin_amd64.tar.gz"
      sha256 "f91b15644f70062023d5c01dcfb1218f5e879e4c5cede99c72026629b46649ab"

      def install
        bin.install "mocktail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/traefik/mocktail/releases/download/v0.2.1/mocktail_v0.2.1_darwin_arm64.tar.gz"
      sha256 "9b702911855acea110c09e9b8a57d5518ae5c2e772ada06553e24866a6e9c4e3"

      def install
        bin.install "mocktail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/traefik/mocktail/releases/download/v0.2.1/mocktail_v0.2.1_linux_amd64.tar.gz"
      sha256 "0a2fa10c0c7d8ebbd869c5da39e0ae1ac64278047d556840a7f981966883df99"

      def install
        bin.install "mocktail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/traefik/mocktail/releases/download/v0.2.1/mocktail_v0.2.1_linux_arm64.tar.gz"
      sha256 "febcae7be5a61a05e7ac759fa34b52f2cf10ee6f6d5238f3fd6cc543a3d54312"

      def install
        bin.install "mocktail"
      end
    end
  end

  test do
    system "echo 0"
  end
end
