# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mocktail < Formula
  desc "Naive code generator that creates mock implementation using testify.mock.
"
  homepage "https://github.com/traefik/mocktail"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/traefik/mocktail/releases/download/v0.3.0/mocktail_v0.3.0_darwin_arm64.tar.gz"
      sha256 "6d8384ec8ad366622a63abaeb1f8959136b3189ec34d7e947a85b99987feb7cd"

      def install
        bin.install "mocktail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/traefik/mocktail/releases/download/v0.3.0/mocktail_v0.3.0_darwin_amd64.tar.gz"
      sha256 "c5448c4eee1ecc0bf68b532da3e874509a19a161e38ca1a4e723c0e0f50d9c79"

      def install
        bin.install "mocktail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/traefik/mocktail/releases/download/v0.3.0/mocktail_v0.3.0_linux_amd64.tar.gz"
      sha256 "535a0a92d59f86a019969d2c4564c8a19555f97ad05a644a93ccb304dd6442aa"

      def install
        bin.install "mocktail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/traefik/mocktail/releases/download/v0.3.0/mocktail_v0.3.0_linux_arm64.tar.gz"
      sha256 "9a35de2db96b2d7a35898723e7afade788b7fe3bbc09517414440538cc1786a7"

      def install
        bin.install "mocktail"
      end
    end
  end

  test do
    system "echo 0"
  end
end
