# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yaegi < Formula
  desc "Yaegi is Another Elegant Go Interpreter.
It powers executable Go scripts and plugins, in embedded interpreters
or interactive shells, on top of the Go runtime.
"
  homepage "https://github.com/traefik/yaegi"
  version "0.9.15"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/traefik/yaegi/releases/download/v0.9.15/yaegi_v0.9.15_darwin_amd64.tar.gz"
    sha256 "cc0de444c05aa278328180a2dea5dc453818c086fa552929747fc9c3e1a9d082"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/traefik/yaegi/releases/download/v0.9.15/yaegi_v0.9.15_darwin_arm64.tar.gz"
    sha256 "8a32ea6745d683d0501fb5c1eb9ba6ece400b1849f97749dfe443bc42add74b1"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/traefik/yaegi/releases/download/v0.9.15/yaegi_v0.9.15_linux_amd64.tar.gz"
    sha256 "a4b768608b5e2248cfcf274cdecc1a900a67ce9577249a0de70cac35c46f80cd"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/traefik/yaegi/releases/download/v0.9.15/yaegi_v0.9.15_linux_armv6.tar.gz"
    sha256 "49ca257c57003e5e4315b5a67177ed1c1ae0ef4defc73be449ad0c6e251d37d3"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/traefik/yaegi/releases/download/v0.9.15/yaegi_v0.9.15_linux_arm64.tar.gz"
    sha256 "f6700a3e8f71d2713a5c3fda2c66733b89ce409dc16ce31bafb121edef0f9d68"
  end

  def install
    bin.install "yaegi"
  end

  test do
    system "#{bin}/yaegi version"
  end
end
